addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.5.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-web-scalajs-bundler"  % "0.20.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-twirl"                % "1.5.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-digest"               % "1.1.4")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
